### PR TITLE
chore(ci): Check broken links

### PR DESCRIPTION
**Pull request by erezrokah**
Fixes https://github.com/cloudquery/docs/issues/173

### CODE REVIEW

**Comment by erezrokah** [comment]
This is blocked by updating our docs to not have 308 redirects

**Comment by erezrokah** [comment]
Thanks for pushing for this to happen @dj-stormtrooper 🚀

**Comment by dj-stormtrooper** [comment]
@erezrokah I think we can enable this action only for merge commits to `main` (cause it's a bottleneck for our PR pipeline, so it might be very annoying for creating PRs in this repo)

image

WDYT?

**Review by yevgenypats — APPROVED** [review]

**Comment by dj-stormtrooper** [comment]
Discussed with `@yevgenypats` that 3 minutes is not so bad, so I'm going to add it to PR pipeline

**Pull request merged**
